source "https://rubygems.org"

gem "bundler"
gem "activesupport", "~> 7.0.7.1"
gem "autoprefixer-rails"
gem "html-proofer"
gem "image_optim"
gem "jekyll"
gem "jekyll-assets"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jemoji"
gem "mini_magick"
gem "sass"
gem "sprockets"
gem "uglifier"
